### ISSUE TITLE
Can't seem to use CardImg

### ISSUE THREAD

**Issue by Anahkiasen** [ahrefs/bs-reactstrap#15]
I'm trying to use a CardImg like this `<CardImg src="source" />` but it seems the `src` attribute gets rejected, should I use some kind of Reason-specific variant?

**Comment by liubko** [comment]
@Anahkiasen hi, bindings are generated out of the [PropTypes](https://github.com/reactstrap/reactstrap/blob/master/src/CardImg.js#L6). `src` prop isn't supported at the moment and has to be added [here](https://github.com/ahrefs/bs-reactstrap/blob/master/src/BsReactstrap__CardImg.re#L4). PR's are welcome :)
