### ISSUE TITLE
Autogenerated based on propTypes?

### ISSUE THREAD

**Issue by praveenperera** [ahrefs/bs-reactstrap#17]
Not a issue, but I was wondering what tool you used to autogenerate the bindings using propTypes.

**Comment by liubko** [comment]
CC @rusty-key ^

**Comment by rusty-key** [comment]
@praveenperera, sorry for the late answer. I don't think I have the last version of the "parser" but it was a pretty straightforward script. Here is what I found: https://gist.github.com/rusty-key/f129f9405790f0c69656530a16bd5f09

Basically, I just parsed files, looking for propTypes and then assembled them into `binding`. Then I checked result and fixed some stuff manually.

**Comment by praveenperera** [comment]
Awesome thanks @rusty-key
