### ISSUE TITLE
enable namespacing in bsconfig

### ISSUE THREAD

**Issue by liubko** [ahrefs/bs-reactstrap#2]
@stfoo as far as I understand you add this `reactstrap...` prefix to avoid name collisions, right?

you can enable namespacing in bsconfig https://bucklescript.github.io/docs/en/build-configuration.html#name-namespace

I think, then you can drop `reactstrap.re`

**Comment by rusty-key** [comment]
Thanks, adopted namespaces: https://github.com/ahrefs/bs-reactstrap/commit/57c449e3072b409fe59060c8788fb597c8970bda
