### ISSUE TITLE
Release generator code

### ISSUE THREAD

**Issue by RasmusKlett** [ahrefs/bs-reactstrap#29]
Would it be possible to release the code used to generate these bindings? I'm debating whether to depend on this library, and not having the option of improving them is a major downside.

**Comment by rusty-key** [comment]
@RasmusKlett, I'll try to find it, but it was some very dirty grep function

**Comment by RasmusKlett** [comment]
Oh no :( You say "was", is this library dead?

**Comment by rusty-key** [comment]
The generator code was a one-off solution to jump-start this project

**Comment by RasmusKlett** [comment]
That makes sense I guess. In that case I understand why it is not useful to have the generator code in the repo.

Maybe the sentence "Currently they are autogenerated based on propTypes" in the Readme should be changed? That was what fooled me into thinking it is continually autogenerated.

**Comment by praveenperera** [comment]
I asked this question as well #17 and @rusty-key posted this link: https://gist.github.com/rusty-key/f129f9405790f0c69656530a16bd5f09 👍
